### ISSUE TITLE
Excelente trabajo!

### ISSUE THREAD

**Issue by ltrujillodev** [Mmaxi1720/desafio-m3#1]
Hola Mmaxi1720, un gusto saludarte!

Me tocó darle una mirada a tu desafío.
Te felicito por haber llegado y completado el desafío del tercer módulo.

Te detallo unas de observaciones que noté:

**MOBILE**
- En el `header`: le aumentaría un poco el `width` del `div class="imagen-logo"` tal vez a 84px, a la imagen `img class="logo"` le pondría un `width` de 50px y mejoraría el flex del `header class="header"` con `align-items: center`.
![image](https://user-images.githubusercontent.com/89029026/151098202-754d6b2c-584a-4001-af19-25312bf1d3c9.png)

- En el `main`, le pondría un `margin: 0` al `h2`.
![image](https://user-images.githubusercontent.com/89029026/151098300-be37900e-65ee-4a1f-b729-a52a712ecda8.png)

- En el footer, no logro comprender muy bien la lógica usada en el `div class="redes"`. No obstante, se le puede agregar un `padding-top` a `img class="imagen-logo-footer"` y agregando un `vertical-align: middle` al `div class="redes"`.
![image](https://user-images.githubusercontent.com/89029026/151102904-1d73ae21-d450-41d8-a07c-e434f7ef1e9c.png)

**DESKTOP**
- Al modificar las dimensiones en el modo responsive, al llegar a los 900px, se rompe el diseño del `main`. Lo mismo sucede con el `div class="formulario"`.
![image](https://user-images.githubusercontent.com/89029026/151104514-35b37f28-ee1e-4567-a77d-78e1ed0e55e7.png)
![image](https://user-images.githubusercontent.com/89029026/151104540-d9645531-16e5-4c40-917e-73d4d041b649.png)

Espero no haber sido muy extenso.

Un saludo, 

Luis

**Comment by Mmaxi1720** [comment]
Buenas Luis!
Muchas gracias por tomarte el tiempo y verlo!
Ahi hice algunas modificaciones, las que me recomendaste sobre todo.
Esperemos que vaya un poco mejor ahora
