### ISSUE TITLE
Review #1 - Detalle en el alinemiento de los elementos.

### ISSUE THREAD

**Issue by FacundoEG** [Mmaxi1720/desafio-m3#2]
Hola Maxi ! como andas? primero que nada te felicito por haber enviado el desafío del modulo 3!

Te comento que estuve viendo la page y en lineas del desafio esta muy bien!

Hay algunas cositas en el modo de "buenas practicas" que me gustaría mostrarte para mejorar:

Por ejemplo, hay elementos del div perfil que quedan metidos dentro del modelo de cajas de la sección "contenedor-main":
![image](https://user-images.githubusercontent.com/79592789/151561724-4f0172ca-a309-4f58-bba4-c11bfdf118b9.png)

Al parecer eso lo separas usando el margin top, pero en teoría los elementos de una sección no puede "invadir" o meterse dentro de otra, ya que para eso mismo esta planteado el modelo de cajas. En este caso deberías usar las propiedades de las secciones padres para poder manejar el contenido de sus hijos, no tratar de usar los margenes para acomodarlos.

Mismo podrías sacarle la propiedad "float" y manejarlo de una forma mas organizada:
![image](https://user-images.githubusercontent.com/79592789/151562285-7b2d62dd-f8d5-4719-8a05-1b50e4612519.png)

Despues el form por ejemplo no quedo muy alineado, fijate que la parte de "escribime" tanto en desktop como en mobile queda alineada a la izquierda:

![image](https://user-images.githubusercontent.com/79592789/151562544-97a4a63c-352f-46f4-a103-d0830bed85ba.png)
![image](https://user-images.githubusercontent.com/79592789/151562578-243e31da-c11c-47bc-8a2c-1a11ddd949bb.png)

En definitiva serían esas cosas los detalles,  te lo voy a dar como aprobado al desafío porque veo que cumplio todas las premisas que se pedían y la verdad que sacando eso esta muy bien, pero te voy a dejar eso a modo de mejora! 

Te mando un saludo y te deseo exitos para el proximo modulo!

**Comment by Mmaxi1720** [comment]
Buenas Facu!
Te agradezco por tomarte el tiempo de verlo, tambien te agradezco por las observaciones!
Ya vamos a ir puliendo los detalles. 
Nuevamente gracias!!
